# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test
on:
    push:

env:
    TEST_REPO: kattecon/gh-app-access-token-gen-test

jobs:
    check:
        name: Test

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: lts/*

            - name: Generate token using app_id, pk and repo-name (1)
              id: test_case_1_gen
              uses: ./
              with:
                  app_id: ${{ secrets.TEST_APP_ID }}
                  private_key: ${{ secrets.TEST_APP_PK }}
                  repository: ${{ env.TEST_REPO }}

            - name: Test access using token from (1)
              env:
                  GH_TOKEN: ${{ steps.test_case_1_gen.outputs.token }}
              run: gh repo view "$TEST_REPO" --json name

            - name: Generate token using app id, pk and installation id (2)
              id: test_case_2_gen
              uses: ./
              with:
                  app_id: ${{ secrets.TEST_APP_ID }}
                  private_key: ${{ secrets.TEST_APP_PK }}
                  installation_id: ${{ secrets.TEST_APP_INST_ID }}

            - name: Test access using token from (2)
              env:
                  GH_TOKEN: ${{ steps.test_case_2_gen.outputs.token }}
              run: gh repo view "$TEST_REPO" --json name
